targets:
  $default:
    sources:
      - lib/**
      - graphql/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql/translink.schema.json
              queries_glob: graphql/stop.query.graphql
              output: 'lib/graphql_api.dart'